/* PRODUCT DETAILS */
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_PRODUCT_DETAIL_FAIL = "GET_PRODUCT_DETAIL_FAIL";

export const GET_PRODUCT_COMMENTS_SUCCESS = "GET_PRODUCT_COMMENTS_SUCCESS";
export const GET_PRODUCT_COMMENTS_FAIL = "GET_PRODUCT_COMMENTS_FAIL";

export const ON_LIKE_COMMENT = "ON_LIKE_COMMENT";
export const ON_LIKE_COMMENT_SUCCESS = "ON_LIKE_COMMENT_SUCCESS";
export const ON_LIKE_COMMENT_FAIL = "ON_LIKE_COMMENT_FAIL";

export const ON_LIKE_REPLY = "ON_LIKE_REPLY";
export const ON_LIKE_REPLY_SUCCESS = "ON_LIKE_REPLY_SUCCESS";
export const ON_LIKE_REPLY_FAIL = "ON_LIKE_REPLY_FAIL";

export const ON_ADD_REPLY = "ON_ADD_REPLY";
export const ON_ADD_REPLY_SUCCESS = "ON_ADD_REPLY_SUCCESS";
export const ON_ADD_REPLY_FAIL = "ON_ADD_REPLY_FAIL";

export const ON_ADD_COMMENT = "ON_ADD_COMMENT";
export const ON_ADD_COMMENT_SUCCESS = "ON_ADD_COMMENT_SUCCESS";
export const ON_ADD_COMMENT_FAIL = "ON_ADD_COMMENT_FAIL";

/* ORDERS */
export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

/**
 * add ORDER
 */
export const ADD_NEW_ORDER = "ADD_NEW_ORDER";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAIL = "ADD_ORDER_FAIL";

/**
 * Edit ORDER
 */
export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";

/**
 * Delete ORDER
 */
export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

/* CART DATA */
export const GET_CART_DATA = "GET_CART_DATA";
export const GET_CART_DATA_SUCCESS = "GET_CART_DATA_SUCCESS";
export const GET_CART_DATA_FAIL = "GET_CART_DATA_FAIL";

/* CUSTOMERS */
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_FAIL = "GET_CUSTOMERS_FAIL";

/**
 * add CUSTOMER
 */
export const ADD_NEW_CUSTOMER = "ADD_NEW_CUSTOMER";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAIL = "ADD_CUSTOMER_FAIL";

/**
 * Edit CUSTOMER
 */
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAIL = "UPDATE_CUSTOMER_FAIL";

/**
 * Delete CUSTOMER
 */
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAIL = "DELETE_CUSTOMER_FAIL";

/* SHOPS */
export const GET_SHOPS = "GET_SHOPS";
export const GET_SHOPS_SUCCESS = "GET_SHOPS_SUCCESS";
export const GET_SHOPS_FAIL = "GET_SHOPS_FAIL";

// Dashboard
export const GET_DASHBOARD = "GET_DASHBOARD";
export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS";

// Categories
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";

export const SHOW_CATEGORY = "SHOW_CATEGORIES";
export const SHOW_CATEGORY_SUCCESS = "SHOW_CATEGORIES_SUCCESS";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";

export const CATEGORY_FILTERS = "CATEGORY_FILTERS";
export const CATEGORY_FILTERS_SUCCESS = "CATEGORY_FILTERS_SUCCESS";

export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";

export const CATEGORY_ERROR = "CATEGORY_ERROR";

// MEASUREMENTS
export const GET_MEASUREMENTS = "GET_MEASUREMENTS";
export const GET_MEASUREMENTS_SUCCESS = "GET_MEASUREMENTS_SUCCESS";

export const SHOW_MEASUREMENT = "SHOW_MEASUREMENT";
export const SHOW_MEASUREMENT_SUCCESS = "SHOW_MEASUREMENT_SUCCESS";

export const ADD_MEASUREMENT = "ADD_MEASUREMENT";
export const ADD_MEASUREMENT_SUCCESS = "ADD_MEASUREMENT_SUCCESS";

export const UPDATE_MEASUREMENT = "UPDATE_MEASUREMENT";
export const UPDATE_MEASUREMENT_SUCCESS = "UPDATE_MEASUREMENT_SUCCESS";

export const DELETE_MEASUREMENT = "DELETE_MEASUREMENT";
export const DELETE_MEASUREMENT_SUCCESS = "DELETE_MEASUREMENT_SUCCESS";

export const MEASUREMENT_ERROR = "MEASUREMENT_ERROR";

// BRANDS
export const GET_BRANDS = "GET_BRANDS";
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";

export const SHOW_BRAND = "SHOW_BRAND";
export const SHOW_BRAND_SUCCESS = "SHOW_BRAND_SUCCESS";

export const ADD_BRAND = "ADD_BRAND";
export const ADD_BRAND_SUCCESS = "ADD_BRAND_SUCCESS";

export const UPDATE_BRAND = "UPDATE_BRAND";
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS";

export const DELETE_BRAND = "DELETE_BRAND";
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS";

export const BRAND_ERROR = "BRAND_ERROR";

// LABELS
export const GET_LABELS = "GET_LABELS";
export const GET_LABELS_SUCCESS = "GET_LABELS_SUCCESS";

export const SHOW_LABEL = "SHOW_LABEL";
export const SHOW_LABEL_SUCCESS = "SHOW_LABEL_SUCCESS";

export const ADD_LABEL = "ADD_LABEL";
export const ADD_LABEL_SUCCESS = "ADD_LABEL_SUCCESS";

export const UPDATE_LABEL = "UPDATE_LABEL";
export const UPDATE_LABEL_SUCCESS = "UPDATE_LABEL_SUCCESS";

export const DELETE_LABEL = "DELETE_LABEL";
export const DELETE_LABEL_SUCCESS = "DELETE_LABEL_SUCCESS";

export const LABEL_ERROR = "LABEL_ERROR";

// PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const SHOW_PRODUCT = "SHOW_PRODUCT";
export const SHOW_PRODUCT_SUCCESS = "SHOW_PRODUCT_SUCCESS";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";

export const PRODUCT_FILTERS = "PRODUCT_FILTERS";
export const PRODUCT_FILTERS_SUCCESS = "PRODUCT_FILTERS_SUCCESS";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const RESET_EDITING_PRODUCT = "RESET_EDITING_PRODUCT";

// TECHNICALS
export const GET_TECHNICALS = "GET_TECHNICALS";
export const GET_TECHNICALS_SUCCESS = "GET_TECHNICALS_SUCCESS";

export const SHOW_TECHNICAL = "SHOW_TECHNICAL";
export const SHOW_TECHNICAL_SUCCESS = "SHOW_TECHNICAL_SUCCESS";

export const ADD_TECHNICAL = "ADD_TECHNICAL";
export const ADD_TECHNICAL_SUCCESS = "ADD_TECHNICAL_SUCCESS";

export const UPDATE_TECHNICAL = "UPDATE_TECHNICAL";
export const UPDATE_TECHNICAL_SUCCESS = "UPDATE_TECHNICAL_SUCCESS";

export const DELETE_TECHNICAL = "DELETE_TECHNICAL";
export const DELETE_TECHNICAL_SUCCESS = "DELETE_TECHNICAL_SUCCESS";

export const TECHNICAL_ERROR = "TECHNICAL_ERROR";
export const GET_TECHNICALS_FAIL = "GET_TECHNICALS_FAIL";

// ATTRIBUTES
export const GET_ATTRIBUTES = "GET_ATTRIBUTES";
export const GET_ATTRIBUTES_SUCCESS = "GET_ATTRIBUTES_SUCCESS";

export const SHOW_ATTRIBUTE = "SHOW_ATTRIBUTE";
export const SHOW_ATTRIBUTE_SUCCESS = "SHOW_ATTRIBUTE_SUCCESS";

export const ADD_ATTRIBUTE = "ADD_ATTRIBUTE";
export const ADD_ATTRIBUTE_SUCCESS = "ADD_ATTRIBUTE_SUCCESS";

export const UPDATE_ATTRIBUTE = "UPDATE_ATTRIBUTE";
export const UPDATE_ATTRIBUTE_SUCCESS = "UPDATE_ATTRIBUTE_SUCCESS";

export const DELETE_ATTRIBUTE = "DELETE_ATTRIBUTE";
export const DELETE_ATTRIBUTE_SUCCESS = "DELETE_ATTRIBUTE_SUCCESS";

export const ATTRIBUTE_ERROR = "ATTRIBUTE_ERROR";
export const GET_ATTRIBUTES_FAIL = "GET_ATTRIBUTES_FAIL";

// ATTRIBUTE GROUPS
export const GET_ATTRIBUTE_GROUPS = "GET_ATTRIBUTE_GROUPS";
export const GET_ATTRIBUTE_GROUPS_SUCCESS = "GET_ATTRIBUTE_GROUPS_SUCCESS";
export const GET_ATTRIBUTE_GROUPS_FAIL = "GET_ATTRIBUTE_GROUPS_FAIL";

export const SHOW_ATTRIBUTE_GROUP = "SHOW_ATTRIBUTE_GROUP";
export const SHOW_ATTRIBUTE_GROUP_SUCCESS = "SHOW_ATTRIBUTE_GROUP_SUCCESS";

export const ADD_ATTRIBUTE_GROUP = "ADD_ATTRIBUTE_GROUP";
export const ADD_ATTRIBUTE_GROUP_SUCCESS = "ADD_ATTRIBUTE_GROUP_SUCCESS";

export const UPDATE_ATTRIBUTE_GROUP = "UPDATE_ATTRIBUTE_GROUP";
export const UPDATE_ATTRIBUTE_GROUP_SUCCESS = "UPDATE_ATTRIBUTE_GROUP_SUCCESS";

export const DELETE_ATTRIBUTE_GROUP = "DELETE_ATTRIBUTE_GROUP";
export const DELETE_ATTRIBUTE_GROUP_SUCCESS = "DELETE_ATTRIBUTE_GROUP_SUCCESS";

export const ATTRIBUTE_GROUP_ERROR = "ATTRIBUTE_GROUP_ERROR";

// ATTRIBUTE VALUES
export const GET_ATTRIBUTE_VALUES = "GET_ATTRIBUTE_VALUES";
export const GET_ATTRIBUTE_VALUES_SUCCESS = "GET_ATTRIBUTE_VALUES_SUCCESS";

export const SHOW_ATTRIBUTE_VALUE = "SHOW_ATTRIBUTE_VALUE";
export const SHOW_ATTRIBUTE_VALUE_SUCCESS = "SHOW_ATTRIBUTE_VALUE_SUCCESS";

export const ADD_ATTRIBUTE_VALUE = "ADD_ATTRIBUTE_VALUE";
export const ADD_ATTRIBUTE_VALUE_SUCCESS = "ADD_ATTRIBUTE_VALUE_SUCCESS";

export const UPDATE_ATTRIBUTE_VALUE = "UPDATE_ATTRIBUTE_VALUE";
export const UPDATE_ATTRIBUTE_VALUE_SUCCESS = "UPDATE_ATTRIBUTE_VALUE_SUCCESS";

export const DELETE_ATTRIBUTE_VALUE = "DELETE_ATTRIBUTE_VALUE";
export const DELETE_ATTRIBUTE_VALUE_SUCCESS = "DELETE_ATTRIBUTE_VALUE_SUCCESS";

export const ATTRIBUTE_VALUE_ERROR = "ATTRIBUTE_VALUE_ERROR";
export const GET_ATTRIBUTE_VALUES_FAIL = "GET_ATTRIBUTE_VALUES_FAIL";

// PRODUCT VARIANTS
export const GET_PRODUCT_VARIANTS = "GET_PRODUCT_VARIANTS";
export const GET_PRODUCT_VARIANTS_SUCCESS = "GET_PRODUCT_VARIANTS_SUCCESS";

export const SHOW_PRODUCT_VARIANT = "SHOW_PRODUCT_VARIANT";
export const SHOW_PRODUCT_VARIANT_SUCCESS = "SHOW_PRODUCT_VARIANT_SUCCESS";

export const ADD_PRODUCT_VARIANT = "ADD_PRODUCT_VARIANT";
export const ADD_PRODUCT_VARIANT_SUCCESS = "ADD_PRODUCT_VARIANT_SUCCESS";

export const UPDATE_PRODUCT_VARIANT = "UPDATE_PRODUCT_VARIANT";
export const UPDATE_PRODUCT_VARIANT_SUCCESS = "UPDATE_PRODUCT_VARIANT_SUCCESS";

export const DELETE_PRODUCT_VARIANT = "DELETE_PRODUCT_VARIANT";
export const DELETE_PRODUCT_VARIANT_SUCCESS = "DELETE_PRODUCT_VARIANT_SUCCESS";

export const PRODUCT_VARIANT_ERROR = "PRODUCT_VARIANT_ERROR";
export const GET_PRODUCT_VARIANTS_FAIL = "GET_PRODUCT_VARIANTS_FAIL";

// DISCOUNTS
export const GET_DISCOUNTS = "GET_DISCOUNTS";
export const GET_DISCOUNTS_SUCCESS = "GET_DISCOUNTS_SUCCESS";

export const SHOW_DISCOUNT = "SHOW_DISCOUNT";
export const SHOW_DISCOUNT_SUCCESS = "SHOW_DISCOUNT_SUCCESS";

export const ADD_DISCOUNT = "ADD_DISCOUNT";
export const ADD_DISCOUNT_SUCCESS = "ADD_DISCOUNT_SUCCESS";

export const UPDATE_DISCOUNT = "UPDATE_DISCOUNT";
export const UPDATE_DISCOUNT_SUCCESS = "UPDATE_DISCOUNT_SUCCESS";

export const DELETE_DISCOUNT = "DELETE_DISCOUNT";
export const DELETE_DISCOUNT_SUCCESS = "DELETE_DISCOUNT_SUCCESS";

export const DISCOUNT_ERROR = "DISCOUNT_ERROR";
export const GET_DISCOUNTS_FAIL = "GET_DISCOUNTS_FAIL";

// COUPONS
export const GET_COUPONS = "GET_COUPONS";
export const GET_COUPONS_SUCCESS = "GET_COUPONS_SUCCESS";

export const SHOW_COUPON = "SHOW_COUPON";
export const SHOW_COUPON_SUCCESS = "SHOW_COUPON_SUCCESS";

export const ADD_COUPON = "ADD_COUPON";
export const ADD_COUPON_SUCCESS = "ADD_COUPON_SUCCESS";

export const UPDATE_COUPON = "UPDATE_COUPON";
export const UPDATE_COUPON_SUCCESS = "UPDATE_COUPON_SUCCESS";

export const DELETE_COUPON = "DELETE_COUPON";
export const DELETE_COUPON_SUCCESS = "DELETE_COUPON_SUCCESS";

export const COUPON_ERROR = "COUPON_ERROR";
export const GET_COUPONS_FAIL = "GET_COUPONS_FAIL";

// SLIDERS
export const GET_SLIDERS = "GET_SLIDERS";
export const GET_SLIDERS_SUCCESS = "GET_SLIDERS_SUCCESS";

export const SHOW_SLIDER = "SHOW_SLIDER";
export const SHOW_SLIDER_SUCCESS = "SHOW_SLIDER_SUCCESS";

export const ADD_SLIDER = "ADD_SLIDER";
export const ADD_SLIDER_SUCCESS = "ADD_SLIDER_SUCCESS";

export const UPDATE_SLIDER = "UPDATE_SLIDER";
export const UPDATE_SLIDER_SUCCESS = "UPDATE_SLIDER_SUCCESS";

export const DELETE_SLIDER = "DELETE_SLIDER";
export const DELETE_SLIDER_SUCCESS = "DELETE_SLIDER_SUCCESS";

export const SLIDER_ERROR = "SLIDER_ERROR";
export const GET_SLIDERS_FAIL = "GET_SLIDERS_FAIL";

// USERS
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const SHOW_USER = "SHOW_USER";
export const SHOW_USER_SUCCESS = "SHOW_USER_SUCCESS";

export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const USER_ERROR = "USER_ERROR";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

// productAttributeActions.js
export const UPDATE_PRODUCT_ATTRIBUTE = "UPDATE_PRODUCT_ATTRIBUTE";
export const UPDATE_PRODUCT_ATTRIBUTE_SUCCESS =
  "UPDATE_PRODUCT_ATTRIBUTE_SUCCESS";

export const GET_PRODUCT_ATTRIBUTE = "GET_PRODUCT_ATTRIBUTE";
export const GET_PRODUCT_ATTRIBUTE_SUCCESS = "GET_PRODUCT_ATTRIBUTE_SUCCESS";

export const PRODUCT_ATTRIBUTE_ERROR = "PRODUCT_ATTRIBUTE_ERROR";

// PAYMENT METHODS
export const GET_PAYMENT_METHODS = "GET_PAYMENT_METHODS";
export const GET_PAYMENT_METHODS_SUCCESS = "GET_PAYMENT_METHODS_SUCCESS";

export const SHOW_PAYMENT_METHOD = "SHOW_PAYMENT_METHOD";
export const SHOW_PAYMENT_METHOD_SUCCESS = "SHOW_PAYMENT_METHOD_SUCCESS";

export const UPDATE_PAYMENT_METHOD = "UPDATE_PAYMENT_METHOD";
export const UPDATE_PAYMENT_METHOD_SUCCESS = "UPDATE_PAYMENT_METHOD_SUCCESS";

export const PAYMENT_METHOD_ERROR = "PAYMENT_METHOD_ERROR";
export const GET_PAYMENT_METHODS_FAIL = "GET_PAYMENT_METHODS_FAIL";

// DELIVERY METHODS
export const GET_DELIVERY_METHODS = "GET_DELIVERY_METHODS";
export const GET_DELIVERY_METHODS_SUCCESS = "GET_DELIVERY_METHODS_SUCCESS";

export const SHOW_DELIVERY_METHOD = "SHOW_DELIVERY_METHOD";
export const SHOW_DELIVERY_METHOD_SUCCESS = "SHOW_DELIVERY_METHOD_SUCCESS";

export const UPDATE_DELIVERY_METHOD = "UPDATE_DELIVERY_METHOD";
export const UPDATE_DELIVERY_METHOD_SUCCESS = "UPDATE_DELIVERY_METHOD_SUCCESS";

export const DELIVERY_METHOD_ERROR = "DELIVERY_METHOD_ERROR";
export const GET_DELIVERY_METHODS_FAIL = "GET_DELIVERY_METHODS_FAIL";

// DELIVERY METHODS Settings
export const GET_DELIVERY_METHODS_SETTINGS = "GET_DELIVERY_METHODS_SETTINGS";
export const GET_DELIVERY_METHODS_SETTINGS_SUCCESS =
  "GET_DELIVERY_METHODS_SETTINGS_SUCCESS";

export const SHOW_DELIVERY_METHOD_SETTINGS = "SHOW_DELIVERY_METHOD_SETTINGS";
export const SHOW_DELIVERY_METHOD_SETTINGS_SUCCESS =
  "SHOW_DELIVERY_METHOD_SETTINGS_SUCCESS";

export const UPDATE_DELIVERY_METHOD_SETTINGS =
  "UPDATE_DELIVERY_METHOD_SETTINGS";
export const UPDATE_DELIVERY_METHOD_SETTINGS_SUCCESS =
  "UPDATE_DELIVERY_METHOD__SETTINGSSUCCESS";

export const DELIVERY_METHOD_SETTINGS_ERROR = "DELIVERY_METHOD_SETTINGS_ERROR";
export const GET_DELIVERY_METHODS_SETTINGS_FAIL =
  "GET_DELIVERY_METHODS_SETTINGS_FAIL";

// CITY PRICE
export const GET_CITY_PRICE = "GET_CITY_PRICE";
export const GET_CITY_PRICE_SUCCESS = "GET_CITY_PRICE_SUCCESS";

export const SHOW_CITY_PRICE = "SHOW_CITY_PRICE";
export const SHOW_CITY_PRICE_SUCCESS = "SHOW_CITY_PRICE_SUCCESS";

export const ADD_CITY_PRICE = "ADD_CITY_PRICE";
export const ADD_CITY_PRICE_SUCCESS = "ADD_CITY_PRICE_SUCCESS";

export const UPDATE_CITY_PRICE = "UPDATE_CITY_PRICE";
export const UPDATE_CITY_PRICE_SUCCESS = "UPDATE_CITY_PRICE_SUCCESS";

export const DELETE_CITY_PRICE = "DELETE_CITY_PRICE";
export const DELETE_CITY_PRICE_SUCCESS = "DELETE_CITY_PRICE_SUCCESS";

export const CITY_PRICE_ERROR = "CITY_PRICE_ERROR";
export const GET_CITY_PRICE_FAIL = "GET_CITY_PRICE_FAIL";

// SETTINGS
export const GET_SETTINGS_REQUEST = "GET_SETTINGS_REQUEST";
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_FAILURE = "GET_SETTINGS_FAILURE";

export const UPDATE_SETTINGS_REQUEST = "UPDATE_SETTINGS_REQUEST";
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS";
export const UPDATE_SETTINGS_FAILURE = "UPDATE_SETTINGS_FAILURE";

// PRODUCT COMMENTS
export const GET_PRODUCT_COMMENTS = "GET_PRODUCT_COMMENTS";
export const UPDATE_COMMENT_STATUS = "UPDATE_COMMENT_STATUS";
export const DELETE_COMMENT = "DELETE_COMMENT";

// PROVINCES COMMENTS
export const GET_PROVINCES = "GET_PROVINCES";
export const GET_PROVINCES_SUCCESS = "GET_PROVINCES_SUCCESS";
export const PROVINCES_ERROR = "PROVINCES_ERROR";

// PRODCUT IMAGE COMMENTS
export const GET_PRODUCT_IMAGE = "GET_PRODUCT_IMAGE";
export const GET_PRODCUT_IMAGE_SUCCESS = "GET_PRODCUT_IMAGE_SUCCESS";
export const UPDATE_PRODUCT_IMAGE = "UPDATE_PRODUCT_IMAGE";
export const UPDATE_PRODCUT_IMAGE_SUCCESS = "UPDATE_PRODCUT_IMAGE_SUCCESS";
export const DELETE_PRODUCT_IMAGE = "DELETE_PRODUCT_IMAGE";
export const DELETE_PRODUCT_IMAGE_SUCCESS = "DELETE_PRODUCT_IMAGE_SUCCESS";
export const PRODCUT_IMAGE_ERROR = "PRODCUT_IMAGE_ERROR";
