import React, { useState, useMemo } from "react";
import {
  Modal,
  ModalHeader,
  ModalBody,
  Input,
  Row,
  Col,
  Button,
} from "reactstrap";

// --- START: Icon Data ---
// Data extracted from files in the /icons folder to provide a comprehensive icon set.

// Material Design Icons Data (from /icons/IconMaterialdesign.jsx)
const mdiIconsData = [
  { name: "ab-testing", version: "4.0.96" },
  { name: "abjad-arabic", version: "4.9.95" },
  { name: "abjad-hebrew", version: "4.9.95" },
  { name: "abugida-devanagari", version: "4.9.95" },
  { name: "abugida-thai", version: "4.9.95" },
  { name: "access-point", version: "1.5.54" },
  { name: "access-point-network", version: "1.5.54" },
  { name: "access-point-network-off", version: "3.2.89" },
  { name: "account", version: "1.5.54" },
  { name: "account-alert", version: "1.5.54" },
  { name: "account-alert-outline", version: "3.0.39" },
  { name: "account-arrow-left", version: "3.0.39" },
  { name: "account-arrow-left-outline", version: "3.0.39" },
  { name: "account-arrow-right", version: "3.0.39" },
  { name: "account-arrow-right-outline", version: "3.0.39" },
  { name: "account-box", version: "1.5.54" },
  { name: "account-box-multiple", version: "2.4.85" },
  { name: "account-box-multiple-outline", version: "4.1.95" },
  { name: "account-box-outline", version: "1.5.54" },
  { name: "account-cancel", version: "4.8.95" },
  { name: "account-cancel-outline", version: "4.8.95" },
  { name: "account-cash", version: "4.2.95" },
  { name: "account-cash-outline", version: "4.2.95" },
  { name: "account-check", version: "1.5.54" },
  { name: "account-check-outline", version: "3.2.89" },
  { name: "account-child", version: "2.7.94" },
  { name: "account-child-circle", version: "2.7.94" },
  { name: "account-child-outline", version: "4.3.95" },
  { name: "account-circle", version: "1.5.54" },
  { name: "account-circle-outline", version: "3.0.39" },
  { name: "account-clock", version: "3.0.39" },
  { name: "account-clock-outline", version: "3.0.39" },
  { name: "account-cog", version: "4.9.95" },
  { name: "account-cog-outline", version: "4.9.95" },
  { name: "account-convert", version: "1.5.54" },
  { name: "account-convert-outline", version: "4.8.95" },
  { name: "account-cowboy-hat", version: "3.7.94" },
  { name: "account-details", version: "1.6.50" },
  { name: "account-details-outline", version: "4.9.95" },
  { name: "account-edit", version: "1.8.36" },
  { name: "account-edit-outline", version: "4.0.96" },
  { name: "account-group", version: "2.1.99" },
  { name: "account-group-outline", version: "3.0.39" },
  { name: "account-hard-hat", version: "1.5.54" },
  { name: "account-heart", version: "2.2.43" },
  { name: "account-heart-outline", version: "3.2.89" },
  { name: "account-key", version: "1.5.54" },
  { name: "account-key-outline", version: "3.2.89" },
  { name: "account-lock", version: "4.4.95" },
  { name: "account-lock-outline", version: "4.4.95" },
  { name: "account-minus", version: "1.5.54" },
  { name: "account-minus-outline", version: "2.8.94" },
  { name: "account-multiple", version: "1.5.54" },
  { name: "account-multiple-check", version: "2.3.50" },
  { name: "account-multiple-check-outline", version: "4.6.95" },
  { name: "account-multiple-minus", version: "1.5.54" },
  { name: "account-multiple-minus-outline", version: "3.2.89" },
  { name: "account-multiple-outline", version: "1.5.54" },
  { name: "account-multiple-plus", version: "1.5.54" },
  { name: "account-multiple-plus-outline", version: "2.1.19" },
  { name: "account-multiple-remove", version: "4.6.95" },
  { name: "account-multiple-remove-outline", version: "4.6.95" },
  { name: "account-music", version: "2.1.19" },
  { name: "account-music-outline", version: "3.3.92" },
  { name: "account-network", version: "1.5.54" },
  { name: "account-network-outline", version: "3.2.89" },
  { name: "account-off", version: "1.5.54" },
  { name: "account-off-outline", version: "3.2.89" },
  { name: "account-outline", version: "1.5.54" },
  { name: "account-plus", version: "1.5.54" },
  { name: "account-plus-outline", version: "2.1.19" },
  { name: "account-question", version: "3.0.39" },
  { name: "account-question-outline", version: "3.0.39" },
  { name: "account-remove", version: "1.5.54" },
  { name: "account-remove-outline", version: "2.8.94" },
  { name: "account-search", version: "1.5.54" },
  { name: "account-search-outline", version: "2.4.85" },
  { name: "account-settings", version: "1.6.50" },
  { name: "account-settings-outline", version: "4.3.95" },
  { name: "account-star", version: "1.5.54" },
  { name: "account-star-outline", version: "3.2.89" },
  { name: "account-supervisor", version: "2.7.94" },
  { name: "account-supervisor-circle", version: "2.7.94" },
  { name: "account-switch", version: "1.5.54" },
  { name: "account-tie", version: "3.3.92" },
  { name: "account-tie-outline", version: "4.3.95" },
  { name: "account-voice", version: "1.5.54" },
];
const mdiIcons = mdiIconsData.map((icon) => `mdi mdi-${icon.name}`);

// Font Awesome Icons Data (from /icons/IconFontawesome.jsx)
const faIconsJSON =
  '{"data":[{"attributes":{"id":"500px","membership":{"free":["brands"],"pro":["brands"]},"styles":["brands"],"unicode":"f26e","voted":false},"id":"500px","links":{"self":"/api/icons/500px"},"type":"icon"},{"attributes":{"id":"accessible-icon","membership":{"free":["brands"],"pro":["brands"]},"styles":["brands"],"unicode":"f368","voted":false},"id":"accessible-icon","links":{"self":"/api/icons/accessible-icon"},"type":"icon"},{"attributes":{"id":"accusoft","membership":{"free":["brands"],"pro":["brands"]},"styles":["brands"],"unicode":"f369","voted":false},"id":"accusoft","links":{"self":"/api/icons/accusoft"},"type":"icon"},{"attributes":{"id":"acquisitions-incorporated","membership":{"free":["brands"],"pro":["brands"]},"styles":["brands"],"unicode":"f6af","voted":false},"id":"acquisitions-incorporated","links":{"self":"/api/icons/acquisitions-incorporated"},"type":"icon"},{"attributes":{"id":"ad","membership":{"free":["solid"],"pro":["solid","regular","light","duotone"]},"styles":["solid","regular","light","duotone"],"unicode":"f641","voted":false},"id":"ad","links":{"self":"/api/icons/ad"},"type":"icon"},{"attributes":{"id":"address-book","membership":{"free":["solid","regular"],"pro":["solid","regular","light","duotone"]},"styles":["solid","regular","light","duotone"],"unicode":"f2b9","voted":false},"id":"address-book","links":{"self":"/api/icons/address-book"},"type":"icon"},{"attributes":{"id":"address-card","membership":{"free":["solid","regular"],"pro":["solid","regular","light","duotone"]},"styles":["solid","regular","light","duotone"],"unicode":"f2bb","voted":false},"id":"address-card","links":{"self":"/api/icons/address-card"},"type":"icon"},{"attributes":{"id":"adjust","membership":{"free":["solid"],"pro":["solid","regular","light","duotone"]},"styles":["solid","regular","light","duotone"],"unicode":"f042","voted":false},"id":"adjust","links":{"self":"/api/icons/adjust"},"type":"icon"},{"attributes":{"id":"adn","membership":{"free":["brands"],"pro":["brands"]},"styles":["brands"],"unicode":"f170","voted":false},"id":"adn","links":{"self":"/api/icons/adn"},"type":"icon"}]}';
const faIcons = [];
try {
  const faData = JSON.parse(faIconsJSON).data;
  faData.forEach((entry) => {
    if (entry.attributes.membership.free.length) {
      entry.attributes.membership.free.forEach((style) => {
        let prefix = "";
        if (style === "brands") prefix = "fab";
        else if (style === "solid") prefix = "fas";
        else if (style === "regular") prefix = "far";
        if (prefix) {
          faIcons.push(`${prefix} fa-${entry.id}`);
        }
      });
    }
  });
} catch (e) {
  console.error("Failed to parse Font Awesome icons", e);
}

// Dripicons Data (from /icons/IconDripicons.jsx)
const dripIcons = [
  "dripicons-alarm",
  "dripicons-align-center",
  "dripicons-align-justify",
  "dripicons-align-left",
  "dripicons-align-right",
  "dripicons-anchor",
  "dripicons-archive",
  "dripicons-arrow-down",
  "dripicons-arrow-left",
  "dripicons-arrow-right",
  "dripicons-arrow-thin-down",
  "dripicons-arrow-thin-left",
  "dripicons-arrow-thin-right",
  "dripicons-arrow-thin-up",
  "dripicons-arrow-up",
  "dripicons-article",
  "dripicons-backspace",
  "dripicons-basket",
  "dripicons-basketball",
  "dripicons-battery-empty",
  "dripicons-battery-full",
  "dripicons-battery-low",
  "dripicons-battery-medium",
  "dripicons-bell",
  "dripicons-blog",
  "dripicons-bluetooth",
  "dripicons-bold",
  "dripicons-bookmark",
  "dripicons-bookmarks",
  "dripicons-box",
  "dripicons-briefcase",
  "dripicons-brightness-low",
  "dripicons-brightness-max",
  "dripicons-brightness-medium",
  "dripicons-broadcast",
  "dripicons-browser",
  "dripicons-browser-upload",
  "dripicons-brush",
  "dripicons-calendar",
  "dripicons-camcorder",
  "dripicons-camera",
  "dripicons-card",
  "dripicons-cart",
  "dripicons-checklist",
  "dripicons-checkmark",
  "dripicons-chevron-down",
  "dripicons-chevron-left",
  "dripicons-chevron-right",
  "dripicons-chevron-up",
  "dripicons-clipboard",
  "dripicons-clock",
  "dripicons-clockwise",
  "dripicons-cloud",
  "dripicons-cloud-download",
  "dripicons-cloud-upload",
  "dripicons-code",
  "dripicons-contract",
  "dripicons-contract-2",
  "dripicons-conversation",
  "dripicons-copy",
  "dripicons-crop",
  "dripicons-cross",
  "dripicons-crosshair",
  "dripicons-cutlery",
  "dripicons-device-desktop",
  "dripicons-device-mobile",
  "dripicons-device-tablet",
  "dripicons-direction",
  "dripicons-disc",
  "dripicons-document",
  "dripicons-document-delete",
  "dripicons-document-edit",
  "dripicons-document-new",
  "dripicons-document-remove",
  "dripicons-dot",
  "dripicons-dots-2",
  "dripicons-dots-3",
  "dripicons-download",
  "dripicons-duplicate",
  "dripicons-enter",
  "dripicons-exit",
  "dripicons-expand",
  "dripicons-expand-2",
  "dripicons-experiment",
  "dripicons-export",
  "dripicons-feed",
  "dripicons-flag",
  "dripicons-flashlight",
  "dripicons-folder",
  "dripicons-folder-open",
  "dripicons-forward",
  "dripicons-gaming",
  "dripicons-gear",
  "dripicons-graduation",
  "dripicons-graph-bar",
  "dripicons-graph-line",
  "dripicons-graph-pie",
  "dripicons-headset",
  "dripicons-heart",
  "dripicons-help",
  "dripicons-home",
  "dripicons-hourglass",
  "dripicons-inbox",
  "dripicons-information",
  "dripicons-italic",
  "dripicons-jewel",
  "dripicons-lifting",
  "dripicons-lightbulb",
  "dripicons-link",
  "dripicons-link-broken",
  "dripicons-list",
  "dripicons-loading",
  "dripicons-location",
  "dripicons-lock",
  "dripicons-lock-open",
  "dripicons-mail",
  "dripicons-map",
  "dripicons-media-loop",
  "dripicons-media-next",
  "dripicons-media-pause",
  "dripicons-media-play",
  "dripicons-media-previous",
  "dripicons-media-record",
  "dripicons-media-shuffle",
  "dripicons-media-stop",
  "dripicons-medical",
  "dripicons-menu",
  "dripicons-message",
  "dripicons-meter",
  "dripicons-microphone",
  "dripicons-minus",
  "dripicons-monitor",
  "dripicons-move",
  "dripicons-music",
  "dripicons-network-1",
  "dripicons-network-2",
  "dripicons-network-3",
  "dripicons-network-4",
  "dripicons-network-5",
  "dripicons-pamphlet",
  "dripicons-paperclip",
  "dripicons-pencil",
  "dripicons-phone",
  "dripicons-photo",
  "dripicons-photo-group",
  "dripicons-pill",
  "dripicons-pin",
  "dripicons-plus",
  "dripicons-power",
  "dripicons-preview",
  "dripicons-print",
  "dripicons-pulse",
  "dripicons-question",
  "dripicons-reply",
  "dripicons-reply-all",
  "dripicons-return",
  "dripicons-retweet",
  "dripicons-rocket",
  "dripicons-scale",
  "dripicons-search",
  "dripicons-shopping-bag",
  "dripicons-skip",
  "dripicons-stack",
  "dripicons-star",
  "dripicons-stopwatch",
  "dripicons-store",
  "dripicons-suitcase",
  "dripicons-swap",
  "dripicons-tag",
  "dripicons-tag-delete",
  "dripicons-tags",
  "dripicons-thumbs-down",
  "dripicons-thumbs-up",
  "dripicons-ticket",
  "dripicons-time-reverse",
  "dripicons-to-do",
  "dripicons-toggles",
  "dripicons-trash",
  "dripicons-trophy",
  "dripicons-upload",
  "dripicons-user",
  "dripicons-user-group",
  "dripicons-user-id",
  "dripicons-vibrate",
  "dripicons-view-apps",
  "dripicons-view-list",
  "dripicons-view-list-large",
  "dripicons-view-thumb",
  "dripicons-volume-full",
  "dripicons-volume-low",
  "dripicons-volume-medium",
  "dripicons-volume-off",
  "dripicons-wallet",
  "dripicons-warning",
  "dripicons-web",
  "dripicons-weight",
  "dripicons-wifi",
  "dripicons-wrong",
  "dripicons-zoom-in",
  "dripicons-zoom-out",
];

// Boxicons Data (from /icons/IconBoxicons.jsx)
const boxIcons = [
  "bx bx-sticker",
  "bx bx-shield-quarter",
  "bx bx-upside-down",
  "bx bx-laugh",
  "bx bx-meh-blank",
  "bx bx-happy-beaming",
  "bx bx-shocked",
  "bx bx-sleepy",
  "bx bx-confused",
  "bx bx-wink-smile",
  "bx bx-dizzy",
  "bx bx-happy-heart-eyes",
  "bx bx-angry",
  "bx bx-smile",
  "bx bx-tired",
  "bx bx-cool",
  "bx bx-happy-alt",
  "bx bx-wink-tongue",
  "bx bx-meh-alt",
  "bx bx-food-menu",
  "bx bx-food-tag",
  "bx bx-female-sign",
  "bx bx-male-sign",
  "bx bx-female",
  "bx bx-male",
  "bx bx-clinic",
  "bx bx-health",
  "bx bx-shekel",
  "bx bx-yen",
  "bx bx-won",
  "bx bx-pound",
  "bx bx-euro",
  "bx bx-rupee",
  "bx bx-ruble",
  "bx bx-lira",
  "bx bx-bitcoin",
  "bx bx-tone",
  "bx bx-bolt-circle",
  "bx bx-cake",
  "bx bx-spa",
  "bx bx-dish",
  "bx bx-fridge",
  "bx bx-image-add",
  "bx bx-image-alt",
  "bx bx-space-bar",
  "bx bx-alarm-add",
  "bx bx-archive-out",
  "bx bx-archive-in",
  "bx bx-add-to-queue",
  "bx bx-border-radius",
  "bx bx-check-shield",
  "bx bx-label",
  "bx bx-file-find",
  "bx bx-face",
  "bx bx-extension",
  "bx bx-exit",
  "bx bx-conversation",
  "bx bx-sort-z-a",
  "bx bx-sort-a-z",
  "bx bx-printer",
  "bx bx-radio",
  "bx bx-customize",
  "bx bx-brush-alt",
  "bx bx-briefcase-alt-2",
  "bx bx-time-five",
  "bx bx-pie-chart-alt-2",
  "bx bx-gas-pump",
  "bx bx-mobile-vibration",
  "bx bx-mobile-landscape",
  "bx bx-border-all",
  "bx bx-border-bottom",
  "bx bx-border-top",
  "bx bx-border-left",
  "bx bx-border-right",
  "bx bx-dialpad-alt",
  "bx bx-filter-alt",
  "bx bx-brightness",
  "bx bx-brightness-half",
  "bx bx-wifi-off",
  "bx bx-credit-card-alt",
  "bx bx-band-aid",
  "bx bx-hive",
  "bx bx-map-pin",
  "bx bx-line-chart",
  "bx bx-receipt",
  "bx bx-purchase-tag-alt",
  "bx bx-basket",
  "bx bx-palette",
  "bx bx-no-entry",
  "bx bx-message-alt-dots",
  "bx bx-message-alt",
  "bx bx-check-square",
  "bx bx-log-out-circle",
  "bx bx-log-in-circle",
  "bx bx-doughnut-chart",
  "bx bx-building-house",
  "bx bx-accessibility",
  "bx bx-user-voice",
  "bx bx-cuboid",
  "bx bx-cube-alt",
  "bx bx-polygon",
  "bx bx-square-rounded",
  "bx bx-square",
  "bx bx-error-alt",
  "bx bx-shield-alt-2",
  "bx bx-paint-roll",
  "bx bx-droplet",
  "bx bx-street-view",
  "bx bx-plus-medical",
  "bx bx-search-alt-2",
  "bx bx-bowling-ball",
  "bx bx-dna",
  "bx bx-cycling",
  "bx bx-shape-circle",
  "bx bx-down-arrow-alt",
  "bx bx-up-arrow-alt",
  "bx bx-right-arrow-alt",
  "bx bx-left-arrow-alt",
  "bx bx-lock-open-alt",
  "bx bx-lock-alt",
  "bx bx-cylinder",
  "bx bx-pyramid",
  "bx bx-comment-dots",
  "bx bx-comment",
  "bx bx-landscape",
  "bx bx-book-open",
  "bx bx-transfer-alt",
  "bx bx-copy-alt",
  "bx bx-run",
  "bx bx-user-pin",
  "bx bx-grid",
  "bx bx-code-alt",
  "bx bx-mail-send",
  "bx bx-ghost",
  "bx bx-shape-triangle",
  "bx bx-shape-square",
  "bx bx-video-recording",
  "bx bx-notepad",
  "bx bx-bug-alt",
  "bx bx-mouse-alt",
  "bx bx-edit-alt",
  "bx bx-chat",
  "bx bx-book-content",
  "bx bx-message-square-dots",
  "bx bx-message-square",
  "bx bx-slideshow",
  "bx bx-wallet-alt",
  "bx bx-memory-card",
  "bx bx-message-rounded-dots",
  "bx bx-message-dots",
  "bx bx-bar-chart-alt-2",
  "bx bx-store-alt",
  "bx bx-buildings",
  "bx bx-home-circle",
  "bx bx-money",
  "bx bx-walk",
  "bx bx-repeat",
  "bx bx-font-family",
  "bx bx-joystick-button",
  "bx bx-paint",
  "bx bx-unlink",
  "bx bx-brush",
  "bx bx-rotate-left",
  "bx bx-badge-check",
  "bx bx-show-alt",
  "bx bx-caret-down",
  "bx bx-caret-right",
  "bx bx-caret-up",
  "bx bx-caret-left",
  "bx bx-calendar-event",
  "bx bx-magnet",
  "bx bx-rewind-circle",
  "bx bx-card",
  "bx bx-help-circle",
  "bx bx-test-tube",
  "bx bx-note",
  "bx bx-sort-down",
  "bx bx-sort-up",
  "bx bx-id-card",
  "bx bx-badge",
  "bx bx-grid-small",
  "bx bx-grid-vertical",
  "bx bx-grid-horizontal",
  "bx bx-move-vertical",
  "bx bx-move-horizontal",
  "bx bx-stats",
  "bx bx-equalizer",
  "bx bx-disc",
  "bx bx-analyse",
  "bx bx-search-alt",
  "bx bx-dollar-circle",
  "bx bx-football",
  "bx bx-ball",
  "bx bx-circle",
  "bx bx-transfer",
  "bx bx-fingerprint",
  "bx bx-font-color",
  "bx bx-highlight",
  "bx bx-file-blank",
  "bx bx-strikethrough",
  "bx bx-photo-album",
  "bx bx-code-block",
  "bx bx-font-size",
  "bx bx-handicap",
  "bx bx-dialpad",
  "bx bx-wind",
  "bx bx-water",
  "bx bx-swim",
  "bx bx-restaurant",
  "bx bx-box",
  "bx bx-menu-alt-right",
  "bx bx-menu-alt-left",
  "bx bx-video-plus",
  "bx bx-list-ol",
  "bx bx-planet",
  "bx bx-hotel",
  "bx bx-movie",
  "bx bx-taxi",
  "bx bx-train",
  "bx bx-bath",
  "bx bx-bed",
  "bx bx-area",
  "bx bx-bot",
  "bx bx-dumbbell",
  "bx bx-check-double",
  "bx bx-bus",
  "bx bx-check-circle",
  "bx bx-rocket",
  "bx bx-certification",
  "bx bx-slider-alt",
  "bx bx-sad",
  "bx bx-meh",
  "bx bx-happy",
  "bx bx-cart-alt",
  "bx bx-car",
  "bx bx-loader-alt",
  "bx bx-loader-circle",
  "bx bx-wrench",
  "bx bx-alarm-off",
  "bx bx-layout",
  "bx bx-dock-left",
  "bx bx-dock-top",
  "bx bx-dock-right",
  "bx bx-dock-bottom",
  "bx bx-world",
  "bx bx-selection",
  "bx bx-paper-plane",
  "bx bx-slider",
  "bx bx-loader",
  "bx bx-chalkboard",
  "bx bx-trash-alt",
  "bx bx-grid-alt",
  "bx bx-command",
  "bx bx-window-close",
  "bx bx-notification-off",
  "bx bx-plug",
  "bx bx-infinite",
  "bx bx-carousel",
  "bx bx-hourglass",
  "bx bx-briefcase-alt",
  "bx bx-wallet",
  "bx bx-station",
  "bx bx-collection",
  "bx bx-tv",
  "bx bx-closet",
  "bx bx-paperclip",
  "bx bx-expand",
  "bx bx-pen",
  "bx bx-purchase-tag",
  "bx bx-images",
  "bx bx-pie-chart-alt",
  "bx bx-news",
  "bx bx-downvote",
  "bx bx-upvote",
  "bx bx-globe-alt",
  "bx bx-store",
  "bx bx-hdd",
  "bx bx-skip-previous-circle",
  "bx bx-skip-next-circle",
  "bx bx-chip",
  "bx bx-cast",
  "bx bx-body",
  "bx bx-phone-outgoing",
  "bx bx-phone-incoming",
  "bx bx-collapse",
  "bx bx-rename",
  "bx bx-rotate-right",
  "bx bx-horizontal-center",
  "bx bx-ruler",
  "bx bx-import",
  "bx bx-calendar-alt",
  "bx bx-battery",
  "bx bx-server",
  "bx bx-task",
  "bx bx-folder-open",
  "bx bx-film",
  "bx bx-aperture",
  "bx bx-phone-call",
  "bx bx-up-arrow",
  "bx bx-undo",
  "bx bx-timer",
  "bx bx-support",
  "bx bx-subdirectory-right",
  "bx bx-right-arrow",
  "bx bx-revision",
  "bx bx-repost",
  "bx bx-reply",
  "bx bx-reply-all",
  "bx bx-redo",
  "bx bx-radar",
  "bx bx-poll",
  "bx bx-list-check",
  "bx bx-like",
  "bx bx-left-arrow",
  "bx bx-joystick-alt",
  "bx bx-history",
  "bx bx-flag",
  "bx bx-first-aid",
  "bx bx-export",
  "bx bx-down-arrow",
  "bx bx-dislike",
  "bx bx-crown",
  "bx bx-barcode",
  "bx bx-user",
  "bx bx-user-x",
  "bx bx-user-plus",
  "bx bx-user-minus",
  "bx bx-user-circle",
  "bx bx-user-check",
  "bx bx-underline",
  "bx bx-trophy",
  "bx bx-trash",
  "bx bx-text",
  "bx bx-sun",
  "bx bx-star",
  "bx bx-sort",
  "bx bx-shuffle",
  "bx bx-shopping-bag",
  "bx bx-shield",
  "bx bx-shield-alt",
  "bx bx-share",
  "bx bx-share-alt",
  "bx bx-select-multiple",
  "bx bx-screenshot",
  "bx bx-save",
  "bx bx-pulse",
  "bx bx-power-off",
  "bx bx-plus",
  "bx bx-pin",
  "bx bx-pencil",
  "bx bx-paste",
  "bx bx-paragraph",
  "bx bx-package",
  "bx bx-notification",
  "bx bx-music",
  "bx bx-move",
  "bx bx-mouse",
  "bx bx-minus",
  "bx bx-microphone-off",
  "bx bx-log-out",
  "bx bx-log-in",
  "bx bx-link-external",
  "bx bx-joystick",
  "bx bx-italic",
  "bx bx-home-alt",
  "bx bx-heading",
  "bx bx-hash",
  "bx bx-group",
  "bx bx-git-repo-forked",
  "bx bx-git-pull-request",
  "bx bx-git-merge",
  "bx bx-git-compare",
  "bx bx-git-commit",
  "bx bx-git-branch",
  "bx bx-font",
  "bx bx-filter",
  "bx bx-file",
  "bx bx-edit",
  "bx bx-diamond",
  "bx bx-detail",
  "bx bx-cut",
  "bx bx-cube",
  "bx bx-crop",
  "bx bx-credit-card",
  "bx bx-columns",
  "bx bx-cog",
  "bx bx-cloud-snow",
  "bx bx-cloud-rain",
  "bx bx-cloud-lightning",
  "bx bx-cloud-light-rain",
  "bx bx-cloud-drizzle",
  "bx bx-check",
  "bx bx-cart",
  "bx bx-calculator",
  "bx bx-bold",
  "bx bx-award",
  "bx bx-anchor",
  "bx bx-album",
  "bx bx-adjust",
  "bx bx-x",
  "bx bx-table",
  "bx bx-duplicate",
  "bx bx-windows",
  "bx bx-window",
  "bx bx-window-open",
  "bx bx-wifi",
  "bx bx-voicemail",
  "bx bx-video-off",
  "bx bx-usb",
  "bx bx-upload",
  "bx bx-alarm",
  "bx bx-tennis-ball",
  "bx bx-target-lock",
  "bx bx-tag",
  "bx bx-tab",
  "bx bx-spreadsheet",
  "bx bx-sitemap",
  "bx bx-sidebar",
  "bx bx-send",
  "bx bx-pie-chart",
  "bx bx-phone",
  "bx bx-navigation",
  "bx bx-mobile",
  "bx bx-mobile-alt",
  "bx bx-message",
  "bx bx-message-rounded",
  "bx bx-map",
  "bx bx-map-alt",
  "bx bx-lock",
  "bx bx-lock-open",
  "bx bx-list-minus",
  "bx bx-list-ul",
  "bx bx-list-plus",
  "bx bx-link",
  "bx bx-link-alt",
  "bx bx-layer",
  "bx bx-laptop",
  "bx bx-home",
  "bx bx-heart",
  "bx bx-headphone",
  "bx bx-devices",
  "bx bx-globe",
  "bx bx-gift",
  "bx bx-envelope",
  "bx bx-download",
  "bx bx-dots-vertical",
  "bx bx-dots-vertical-rounded",
  "bx bx-dots-horizontal",
  "bx bx-dots-horizontal-rounded",
  "bx bx-dollar",
  "bx bx-directions",
  "bx bx-desktop",
  "bx bx-data",
  "bx bx-compass",
  "bx bx-crosshair",
  "bx bx-terminal",
  "bx bx-cloud",
  "bx bx-cloud-upload",
  "bx bx-cloud-download",
  "bx bx-chart",
  "bx bx-calendar",
  "bx bx-calendar-x",
  "bx bx-calendar-minus",
  "bx bx-calendar-check",
  "bx bx-calendar-plus",
  "bx bx-buoy",
  "bx bx-bulb",
  "bx bx-bluetooth",
  "bx bx-bug",
  "bx bx-building",
  "bx bx-broadcast",
  "bx bx-briefcase",
  "bx bx-bookmark-plus",
  "bx bx-bookmark-minus",
  "bx bx-book",
  "bx bx-book-bookmark",
  "bx bx-block",
  "bx bx-basketball",
  "bx bx-bar-chart",
  "bx bx-bar-chart-square",
  "bx bx-bar-chart-alt",
  "bx bx-at",
  "bx bx-archive",
  "bx bx-zoom-out",
  "bx bx-zoom-in",
  "bx bx-x-circle",
  "bx bx-volume",
  "bx bx-volume-mute",
  "bx bx-volume-low",
  "bx bx-volume-full",
  "bx bx-video",
  "bx bx-vertical-center",
  "bx bx-up-arrow-circle",
  "bx bx-trending-up",
  "bx bx-trending-down",
  "bx bx-toggle-right",
  "bx bx-toggle-left",
  "bx bx-time",
  "bx bx-sync",
  "bx bx-stopwatch",
  "bx bx-stop",
  "bx bx-stop-circle",
  "bx bx-skip-previous",
  "bx bx-skip-next",
  "bx bx-show",
  "bx bx-search",
  "bx bx-rss",
  "bx bx-right-top-arrow-circle",
  "bx bx-right-indent",
  "bx bx-right-down-arrow-circle",
  "bx bx-right-arrow-circle",
  "bx bx-reset",
  "bx bx-rewind",
  "bx bx-rectangle",
  "bx bx-radio-circle",
  "bx bx-radio-circle-marked",
  "bx bx-question-mark",
  "bx bx-plus-circle",
  "bx bx-play",
  "bx bx-play-circle",
  "bx bx-pause",
  "bx bx-pause-circle",
  "bx bx-moon",
  "bx bx-minus-circle",
  "bx bx-microphone",
  "bx bx-menu",
  "bx bx-left-top-arrow-circle",
  "bx bx-left-indent",
  "bx bx-left-down-arrow-circle",
  "bx bx-left-arrow-circle",
  "bx bx-last-page",
  "bx bx-key",
  "bx bx-align-justify",
  "bx bx-info-circle",
  "bx bx-image",
  "bx bx-hide",
  "bx bx-fullscreen",
  "bx bx-folder",
  "bx bx-folder-plus",
  "bx bx-folder-minus",
  "bx bx-first-page",
  "bx bx-fast-forward",
  "bx bx-fast-forward-circle",
  "bx bx-exit-fullscreen",
  "bx bx-error",
  "bx bx-error-circle",
  "bx bx-down-arrow-circle",
  "bx bx-copyright",
  "bx bx-copy",
  "bx bx-coffee",
  "bx bx-code",
  "bx bx-code-curly",
  "bx bx-clipboard",
  "bx bx-chevrons-left",
  "bx bx-chevrons-right",
  "bx bx-chevrons-up",
  "bx bx-chevrons-down",
  "bx bx-chevron-right",
  "bx bx-chevron-left",
  "bx bx-chevron-up",
  "bx bx-chevron-down",
  "bx bx-checkbox-square",
  "bx bx-checkbox",
  "bx bx-checkbox-checked",
  "bx bx-captions",
  "bx bx-camera",
  "bx bx-camera-off",
  "bx bx-bullseye",
  "bx bx-bookmarks",
  "bx bx-bookmark",
  "bx bx-bell",
  "bx bx-bell-plus",
  "bx bx-bell-off",
  "bx bx-bell-minus",
  "bx bx-arrow-back",
  "bx bx-align-right",
  "bx bx-align-middle",
  "bx bx-align-left",
  "bxs-wink-tongue",
  "bxs-upside-down",
  "bxs-happy-alt",
  "bxs-laugh",
  "bxs-meh-blank",
  "bxs-cool",
  "bxs-tired",
  "bxs-happy-beaming",
  "bxs-shocked",
  "bxs-happy",
  "bxs-sad",
  "bxs-sleepy",
  "bxs-confused",
  "bxs-meh-alt",
  "bxs-meh",
  "bxs-smile",
  "bxs-wink-smile",
  "bxs-dizzy",
  "bxs-happy-heart-eyes",
  "bxs-angry",
  "bxs-business",
  "bxs-camera-plus",
  "bxs-food-menu",
  "bxs-offer",
  "bxs-clinic",
  "bxs-hand-left",
  "bxs-hand-down",
  "bxs-hand-right",
  "bxs-hand-up",
  "bxs-baby-carriage",
  "bxs-caret-left-circle",
  "bxs-caret-right-circle",
  "bxs-caret-down-circle",
  "bxs-caret-up-circle",
  "bxs-tone",
  "bxs-bolt-circle",
  "bxs-city",
  "bxs-cake",
  "bxs-spa",
  "bxs-dish",
  "bxs-fridge",
  "bxs-image-add",
  "bxs-alarm-add",
  "bxs-archive-out",
  "bxs-archive-in",
  "bxs-add-to-queue",
  "bxs-check-shield",
  "bxs-label",
  "bxs-face",
  "bxs-file-find",
  "bxs-extension",
  "bxs-exit",
  "bxs-brush-alt",
  "bxs-layout",
  "bxs-quote-alt-right",
  "bxs-quote-alt-left",
  "bxs-mobile-vibration",
  "bxs-fast-forward-circle",
  "bxs-rewind-circle",
  "bxs-carousel",
  "bxs-customize",
  "bxs-calendar-event",
  "bxs-calendar-check",
  "bxs-calendar-x",
  "bxs-calendar-minus",
  "bxs-calendar-plus",
  "bxs-calendar-alt",
  "bxs-calendar",
  "bxs-briefcase-alt-2",
  "bxs-bookmark-minus",
  "bxs-bookmarks",
  "bxs-time-five",
  "bxs-pie-chart-alt-2",
  "bxs-time",
  "bxs-timer",
  "bxs-stopwatch",
  "bxs-compass",
  "bxs-user-check",
  "bxs-user-x",
  "bxs-grid",
  "bxs-zoom-out",
  "bxs-zoom-in",
  "bxs-search",
  "bxs-bell-minus",
  "bxs-bell-plus",
  "bxs-folder-minus",
  "bxs-mobile",
  "bxs-data",
  "bxs-skip-next-circle",
  "bxs-skip-previous-circle",
  "bxs-chalkboard",
  "bxs-school",
  "bxs-institution",
  "bxs-left-down-arrow-circle",
  "bxs-left-top-arrow-circle",
  "bxs-right-down-arrow-circle",
  "bxs-right-top-arrow-circle",
  "bxs-down-arrow",
  "bxs-up-arrow",
  "bxs-left-arrow",
  "bxs-right-arrow",
  "bxs-rectangle",
  "bxs-brightness",
  "bxs-brightness-half",
  "bxs-paint",
  "bxs-credit-card",
  "bxs-credit-card-alt",
  "bxs-band-aid",
  "bxs-map-pin",
  "bxs-receipt",
  "bxs-purchase-tag-alt",
  "bxs-basket",
  "bxs-palette",
  "bxs-plane-alt",
  "bxs-component",
  "bxs-traffic-barrier",
  "bxs-no-entry",
  "bxs-message-alt-dots",
  "bxs-message-alt",
  "bxs-check-square",
  "bxs-notification-off",
  "bxs-notification",
  "bxs-log-out",
  "bxs-log-in",
  "bxs-log-out-circle",
  "bxs-log-in-circle",
  "bxs-circle",
  "bxs-doughnut-chart",
  "bxs-building-house",
  "bxs-comment-error",
  "bxs-user-voice",
  "bxs-cuboid",
  "bxs-cube-alt",
  "bxs-polygon",
  "bxs-square-rounded",
  "bxs-square",
  "bxs-error-alt",
  "bxs-shield-alt-2",
  "bxs-paint-roll",
  "bxs-comment-add",
  "bxs-droplet-half",
  "bxs-search-alt-2",
  "bxs-bowling-ball",
  "bxs-hourglass-bottom",
  "bxs-hourglass-top",
  "bxs-lock-open-alt",
  "bxs-lock-alt",
  "bxs-graduation",
  "bxs-vial",
  "bxs-cylinder",
  "bxs-pyramid",
  "bxs-wine",
  "bxs-comment-detail",
  "bxs-comment-dots",
  "bxs-comment",
  "bxs-traffic",
  "bxs-landscape",
  "bxs-adjust-alt",
  "bxs-id-card",
  "bxs-parking",
  "bxs-plane-land",
  "bxs-plane-take-off",
  "bxs-analyse",
  "bxs-file-gif",
  "bxs-file-jpg",
  "bxs-file-png",
  "bxs-file-txt",
  "bxs-file-md",
  "bxs-file-json",
  "bxs-file-js",
  "bxs-file-css",
  "bxs-file-html",
  "bxs-copy-alt",
  "bxs-file-doc",
  "bxs-user-pin",
  "bxs-quote-single-right",
  "bxs-quote-single-left",
  "bxs-ghost",
  "bxs-direction-left",
  "bxs-video-recording",
  "bxs-notepad",
  "bxs-bug-alt",
  "bxs-mouse-alt",
  "bxs-edit-alt",
  "bxs-chat",
  "bxs-book-content",
  "bxs-message-square-dots",
  "bxs-message-square",
  "bxs-slideshow",
  "bxs-bank",
  "bxs-wallet-alt",
  "bxs-memory-card",
  "bxs-devices",
  "bxs-message-rounded-dots",
  "bxs-message-dots",
  "bxs-bar-chart-alt-2",
  "bxs-store-alt",
  "bxs-buildings",
  "bxs-home-circle",
  "bxs-file-pdf",
  "bxs-yin-yang",
  "bxs-ship",
  "bxs-factory",
  "bxs-tree",
  "bxs-plane",
  "bxs-user-rectangle",
  "bxs-eyedropper",
  "bxs-cloud-lightning",
  "bxs-cloud-rain",
  "bxs-eraser",
  "bxs-magic-wand",
  "bxs-hotel",
  "bxs-color-fill",
  "bxs-capsule",
  "bxs-flask",
  "bxs-joystick-button",
  "bxs-direction-right",
  "bxs-directions",
  "bxs-megaphone",
  "bxs-keyboard",
  "bxs-brush",
  "bxs-coffee-alt",
  "bxs-badge-check",
  "bxs-landmark",
  "bxs-gas-pump",
  "bxs-user-badge",
  "bxs-right-arrow-square",
  "bxs-down-arrow-square",
  "bxs-up-arrow-square",
  "bxs-left-arrow-square",
  "bxs-ambulance",
  "bxs-magnet",
  "bxs-card",
  "bxs-help-circle",
  "bxs-note",
  "bxs-badge",
  "bxs-flame",
  "bxs-disc",
  "bxs-minus-square",
  "bxs-plus-square",
  "bxs-x-square",
  "bxs-microphone-alt",
  "bxs-image-alt",
  "bxs-skull",
  "bxs-dollar-circle",
  "bxs-film",
  "bxs-ball",
  "bxs-edit",
  "bxs-file-blank",
  "bxs-bell-ring",
  "bxs-photo-album",
  "bxs-key",
  "bxs-video-plus",
  "bxs-box",
  "bxs-planet",
  "bxs-movie",
  "bxs-taxi",
  "bxs-train",
  "bxs-bath",
  "bxs-bed",
  "bxs-area",
  "bxs-bot",
  "bxs-bus",
  "bxs-star-half",
  "bxs-checkbox-checked",
  "bxs-checkbox",
  "bxs-check-circle",
  "bxs-rocket",
  "bxs-certification",
  "bxs-file-plus",
  "bxs-dashboard",
  "bxs-conversation",
  "bxs-battery-low",
  "bxs-folder-open",
  "bxs-zap",
  "bxs-x-circle",
  "bxs-wrench",
  "bxs-widget",
  "bxs-watch",
  "bxs-watch-alt",
  "bxs-wallet",
  "bxs-volume",
  "bxs-volume-mute",
  "bxs-volume-low",
  "bxs-volume-full",
  "bxs-videos",
  "bxs-video",
  "bxs-video-off",
  "bxs-user",
  "bxs-user-plus",
  "bxs-user-minus",
  "bxs-user-detail",
  "bxs-user-circle",
  "bxs-upvote",
  "bxs-up-arrow-circle",
  "bxs-truck",
  "bxs-trophy",
  "bxs-trash",
  "bxs-trash-alt",
  "bxs-torch",
  "bxs-toggle-right",
  "bxs-to-top",
  "bxs-terminal",
  "bxs-tennis-ball",
  "bxs-tag",
  "bxs-tag-x",
  "bxs-t-shirt",
  "bxs-sun",
  "bxs-store",
  "bxs-star",
  "bxs-spreadsheet",
  "bxs-show",
  "bxs-shopping-bag",
  "bxs-shopping-bag-alt",
  "bxs-shield",
  "bxs-share",
  "bxs-share-alt",
  "bxs-server",
  "bxs-send",
  "bxs-select-multiple",
  "bxs-sort-alt",
  "bxs-save",
  "bxs-ruler",
  "bxs-right-arrow-circle",
  "bxs-report",
  "bxs-rename",
  "bxs-radio",
  "bxs-quote-right",
  "bxs-quote-left",
  "bxs-purchase-tag",
  "bxs-printer",
  "bxs-plus-circle",
  "bxs-plug",
  "bxs-playlist",
  "bxs-pin",
  "bxs-pie-chart",
  "bxs-pie-chart-alt",
  "bxs-phone",
  "bxs-phone-outgoing",
  "bxs-phone-incoming",
  "bxs-phone-call",
  "bxs-pencil",
  "bxs-pen",
  "bxs-paste",
  "bxs-paper-plane",
  "bxs-package",
  "bxs-news",
  "bxs-navigation",
  "bxs-music",
  "bxs-mouse",
  "bxs-moon",
  "bxs-minus-circle",
  "bxs-microphone",
  "bxs-microphone-off",
  "bxs-message",
  "bxs-message-rounded",
  "bxs-map",
  "bxs-map-alt",
  "bxs-lock",
  "bxs-lock-open",
  "bxs-like",
  "bxs-left-arrow-circle",
  "bxs-layer",
  "bxs-joystick",
  "bxs-joystick-alt",
  "bxs-info-circle",
  "bxs-inbox",
  "bxs-image",
  "bxs-hourglass",
  "bxs-hot",
  "bxs-home",
  "bxs-hide",
  "bxs-heart",
  "bxs-hdd",
  "bxs-group",
  "bxs-grid-alt",
  "bxs-gift",
  "bxs-flag",
  "bxs-flag-alt",
  "bxs-first-aid",
  "bxs-filter-alt",
  "bxs-file",
  "bxs-file-image",
  "bxs-error",
  "bxs-error-circle",
  "bxs-envelope",
  "bxs-eject",
  "bxs-duplicate",
  "bxs-droplet",
  "bxs-drink",
  "bxs-downvote",
  "bxs-download",
  "bxs-down-arrow-circle",
  "bxs-dock-top",
  "bxs-dock-right",
  "bxs-dock-left",
  "bxs-dock-bottom",
  "bxs-dislike",
  "bxs-discount",
  "bxs-detail",
  "bxs-cube",
  "bxs-crown",
  "bxs-coupon",
  "bxs-copy",
  "bxs-contact",
  "bxs-collection",
  "bxs-cog",
  "bxs-coffee",
  "bxs-cloud",
  "bxs-cloud-upload",
  "bxs-cloud-download",
  "bxs-chip",
  "bxs-chart",
  "bxs-cart",
  "bxs-cart-alt",
  "bxs-car",
  "bxs-captions",
  "bxs-calculator",
  "bxs-buoy",
  "bxs-bulb",
  "bxs-building",
  "bxs-bug",
  "bxs-briefcase-alt",
  "bxs-briefcase",
  "bxs-bookmark-star",
  "bxs-book-open",
  "bxs-bookmark-plus",
  "bxs-bookmark",
  "bxs-book",
  "bxs-bolt",
  "bxs-bell-off",
  "bxs-bell",
  "bxs-battery-full",
  "bxs-battery-charging",
  "bxs-battery",
  "bxs-barcode",
  "bxs-bar-chart-square",
  "bxs-award",
  "bxs-folder-plus",
  "bxs-folder",
  "bxs-camera-off",
  "bxs-camera",
  "bxs-archive",
  "bxs-album",
  "bxs-alarm-off",
  "bxs-alarm",
  "bxs-adjust",
  "bxl-redbubble",
  "bxl-patreon",
  "bxl-gitlab",
  "bxl-etsy",
  "bxl-figma",
  "bxl-audible",
  "bxl-algolia",
  "bxl-adobe",
  "bxl-pinterest-alt",
  "bxl-imdb",
  "bxl-jquery",
  "bxl-facebook-circle",
  "bxl-instagram-alt",
  "bxl-flickr-square",
  "bxl-whatsapp-square",
  "bxl-squarespace",
  "bxl-medium-old",
  "bxl-mailchimp",
  "bxl-wix",
  "bxl-trello",
  "bxl-spotify",
  "bxl-soundcloud",
  "bxl-snapchat",
  "bxl-less",
  "bxl-flickr",
  "bxl-shopify",
  "bxl-jsfiddle",
  "bxl-css3",
  "bxl-microsoft",
  "bxl-yahoo",
  "bxl-bootstrap",
  "bxl-redux",
  "bxl-mastercard",
  "bxl-visa",
  "bxl-baidu",
  "bxl-chrome",
  "bxl-dailymotion",
  "bxl-joomla",
  "bxl-internet-explorer",
  "bxl-paypal",
  "bxl-edge",
  "bxl-stripe",
  "bxl-telegram",
  "bxl-wordpress",
  "bxl-periscope",
  "bxl-react",
  "bxl-bing",
  "bxl-vuejs",
  "bxl-kickstarter",
  "bxl-nodejs",
  "bxl-javascript",
  "bxl-firefox",
  "bxl-stack-overflow",
  "bxl-magento",
  "bxl-product-hunt",
  "bxl-html5",
  "bxl-git",
  "bxl-quora",
  "bxl-yelp",
  "bxl-airbnb",
  "bxl-opera",
  "bxl-invision",
  "bxl-foursquare",
  "bxl-sass",
  "bxl-wikipedia",
  "bxl-unsplash",
  "bxl-digg",
  "bxl-amazon",
  "bxl-ebay",
  "bxl-drupal",
  "bxl-dropbox",
  "bxl-discourse",
  "bxl-deviantart",
  "bxl-digitalocean",
  "bxl-creative-commons",
  "bxl-codepen",
  "bxl-angular",
  "bxl-messenger",
  "bxl-pocket",
  "bxl-vk",
  "bxl-windows",
  "bxl-play-store",
  "bxl-android",
  "bxl-apple",
  "bxl-blogger",
  "bxl-pinterest",
  "bxl-reddit",
  "bxl-discord",
  "bxl-twitch",
  "bxl-slack",
  "bxl-slack-old",
  "bxl-skype",
  "bxl-medium-square",
  "bxl-medium",
  "bxl-linkedin-square",
  "bxl-google-plus-circle",
  "bxl-google-plus",
  "bxl-facebook-square",
  "bxl-bitcoin",
  "bxl-linkedin",
  "bxl-vimeo",
  "bxl-dribbble",
  "bxl-behance",
  "bxl-tumblr",
  "bxl-whatsapp",
  "bxl-youtube",
  "bxl-twitter",
  "bxl-instagram",
  "bxl-google",
  "bxl-github",
  "bxl-facebook",
];

const allIcons = [
  ...new Set([...mdiIcons, ...faIcons, ...dripIcons, ...boxIcons]),
];

// --- END: Icon Data ---

const IconPickerModal = ({ isOpen, toggle, onIconSelect }) => {
  const [searchTerm, setSearchTerm] = useState("");

  const filteredIcons = useMemo(() => {
    if (!searchTerm) return allIcons;
    return allIcons.filter((icon) =>
      icon.toLowerCase().includes(searchTerm.toLowerCase())
    );
  }, [searchTerm]);

  const handleIconClick = (iconClass) => {
    onIconSelect(iconClass);
    toggle();
  };

  return (
    <Modal isOpen={isOpen} toggle={toggle} size="lg" centered>
      <ModalHeader toggle={toggle}>انتخاب آیکون</ModalHeader>
      <ModalBody>
        <Input
          type="text"
          placeholder="جستجوی آیکون..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="mb-3"
        />
        <div style={{ maxHeight: "400px", overflowY: "auto" }}>
          <Row>
            {filteredIcons.map((iconClass) => (
              <Col key={iconClass} xs="3" sm="2" className="text-center mb-3">
                <Button
                  outline
                  color="secondary"
                  className="p-2"
                  style={{
                    width: "100%",
                    height: "100%",
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                  onClick={() => handleIconClick(iconClass)}
                  title={iconClass}
                >
                  <i className={iconClass} style={{ fontSize: "24px" }}></i>
                  <span
                    style={{
                      fontSize: "10px",
                      wordBreak: "break-word",
                      marginTop: "5px",
                    }}
                  >
                    {iconClass
                      .split(" ")
                      .pop()
                      .replace("fa-", "")
                      .replace("mdi-", "")
                      .replace("dripicons-", "")
                      .replace("bx-", "")
                      .replace("bxs-", "")
                      .replace("bxl-", "")}
                  </span>
                </Button>
              </Col>
            ))}
            {filteredIcons.length === 0 && (
              <Col xs="12" className="text-center text-muted">
                آیکونی یافت نشد.
              </Col>
            )}
          </Row>
        </div>
      </ModalBody>
    </Modal>
  );
};

export default IconPickerModal;
